#!/bin/sh
### BEGIN INIT INFO
# Provides:  script_port1
# Required-Start: $syslog $remote_fs
# Required-Stop: $syslog $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short Description: Aggerater Board Port1 starting script
# Description:   Port1 running script 
### END INIT INFO

#Author:RET Embdded Linux Team

NAME=script_port1
SCRIPTNAME=/etc/init.d/script_port1

#Start and stop Run - levels
start on runlevel [2345]
stop on runlevel [!2345]


echo "PORT1 VVSN"

sudo sh /home/lemaker/port1.sh

#exit 0
