#!/bin/sh
### BEGIN INIT INFO
# Provides:  script_port2
# Required-Start: $syslog $remote_fs
# Required-Stop: $syslog $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short Description: Aggerater Board Port1 starting script
# Description:   Port2 running script 
### END INIT INFO

#Author: RET Embdded Linux Team.

NAME=script_port2
SCRIPTNAME=/etc/init.d/script_port2

#Start and stop Run - levels
start on runlevel [2345]
stop on runlevel [!2345]


echo "PORT2 VVSN"

sudo sh /home/lemaker/port2_agila.sh

#exit 0
