#!/bin/sh
### BEGIN INIT INFO
# Provides:  script_port3
# Required-Start: $syslog $remote_fs
# Required-Stop: $syslog $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short Description: Aggerater Board Port1 starting script
# Description:   Port3 running script 
### END INIT INFO

#Author: RET Embdded Linux Team.

NAME=script_port3
SCRIPTNAME=/etc/init.d/script_port1

#Start and stop Run - levels
start on runlevel [2345]
stop on runlevel [!2345]


echo "PORT3 VVSN"

sudo sh /home/lemaker/port3.sh

#exit 0
