#!/bin/sh
### BEGIN INIT INFO
# Provides:  switch_ret
# Required-Start: $syslog $remote_fs
# Required-Stop: $syslog $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short Description: Switch Initial configuration script for Aggerater  
# Description: network configure switch script
### END INIT INFO

#Author: RET Embedded Linux Team

NAME=switch_ret
SCRIPTNAME=/etc/init.d/switch_ret

#Start and stop Run - levels
start on runlevel [2345]
stop on runlevel [!2345]


echo "Switch VVSN"

sudo sh /home/lemaker/Switch/switch5.sh

#exit 0
